### ISSUE TITLE
Rearrange entries?

### ISSUE THREAD

**Issue by Hairo** [51n7/kMenu#4]
Any way to rearrange entries without removing them and adding them again the preferred order?

**Comment by 51n7** [comment]
I was afraid someone would ask this, it really depends if there's a drag drop sort component in QML but I'll see what I can find.

**Comment by 51n7** [comment]
#### Work In Progress:

![](https://github.com/user-attachments/assets/8a3567d2-19d0-4a60-a315-890e51d81a36)

**Comment by 51n7** [comment]
@Hairo you might have to delete and re-add your menu items for this to work but let me know how it goes. I've repackaged the plasmoid file and also reuploaded it to the [KDE store](https://www.pling.com/p/2154894/).

![](https://github.com/user-attachments/assets/a11b7ba7-130d-4b59-bd1f-19d450ff6f14)

**Comment by 51n7** [comment]
In case the icons need to be reset, the default used are:
```
About This Computer = help-hint
System Preferences... = settings-configure
App Store... = update-none
Force Quit... = error
Sleep = system-suspend
Restart... = system-reboot
Shut Down... = system-shutdown
Lock Screen = system-lock-screen
Log Out = system-log-out
```

**Comment by 51n7** [comment]
closing this ticket due to lack of feedback and also being complete.

**Comment by Hairo** [comment]
Sorry, seems i missed the notifications, looks good :+1:
