### ISSUE TITLE
It is impossible to re-open an application

### ISSUE THREAD

**Issue by buufmax** [51n7/kMenu#6]
It is impossible to re-open an application that it was once opened.

Open one App from kMenu , try to open another window. Won't let it.

Taskbar with right-click have a feature "New Window", or "Open New Window".

**Comment by 51n7** [comment]
Wow is that kTile? It looks great with that theme and icons.

I think I understand your problem but the solution might be how you're launching the application from kMenu. Try adding `konsole &`:

![](https://github.com/user-attachments/assets/8ab13fd5-945e-4b6a-906f-40c99080f502)

When testing this I run `konsole` in command line and it launches the application by attaching the launch process to the shell session, by adding `&` the launch process will run in the background. I think this is what's effecting kMenu as launching the application once then blocks the plasmoid from launching again until the application is closed.

This is working for me now and selecting "Konsole" from the menu always opens a new window. Let me know if it works for you.

**Comment by buufmax** [comment]
Yeah that's your kMenu, it is amazing, I like that it is so simple and so possible to build such a well-arranged app. You have done an extraordinary job creating such an opportunity. Thank you.

Indeed adding "&" fixed my request, I should have thought of this myself.

Yeah it is fixed thanks, close this ticket when you please.

**Comment by 51n7** [comment]
Thanks! I'm happy to help, closing ticket.
